local a = {
  bg = '#282A36',
  fg = '#F8F8F2',
  selection = '#44475A',
  comment = '#6272A4',
  red = '#FF5555',
  orange = '#FFB86C',
  yellow = '#F1FA8C',
  green = '#50fa7b',
  purple = '#BD93F9',
  cyan = '#8BE9FD',
  pink = '#FF79C6',
  bright_red = '#FF6E6E',
  bright_green = '#69FF94',
  bright_yellow = '#FFFFA5',
  bright_blue = '#D6ACFF',
  bright_magenta = '#FF92DF',
  bright_cyan = '#A4FFFF',
  bright_white = '#FFFFFF',
  menu = '#21222C',
  visual = '#3E4452',
  gutter_fg = '#4B5263',
  nontext = '#3B4048',
  white = '#ABB2BF',
  black = '#191A21',
}

local theme = require('dracula').colors()

local colors = {
  white = theme.white,
  bg = theme.nontext,
  bg_highlight = theme.nontext,
  normal = theme.bright_green,
  insert = theme.bright_cyan,
  command = theme.orange,
  visual = theme.bright_purple,
  replace = theme.bright_red,
  diffAdd = theme.bright_green,
  diffModified = theme.orange,
  diffDeleted = theme.bright_red,
  trace = theme.orange,
  hint = theme.bright_cyan,
  info = theme.bright_green,
  error = theme.bright_red,
  warn = theme.orange,
  floatBorder = theme.bright_blue,
  selection_caret = theme.bright_blue,
}
return colors
