local theme = {
  bg_0 = '#181818',
  bg_1 = '#252525',
  bg_2 = '#3B3B3B',
  dim_0 = '#777777',
  fg_0 = '#B9B9B9',
  fg_1 = '#DEDEDE',
  red = '#ED4A46',
  green = '#70B433',
  yellow = '#DBB32D',
  blue = '#368AEB',
  magenta = '#EB6EB7',
  cyan = '#3FC5B7',
  orange = '#E67F43',
  violet = '#A580E2',
  br_red = '#FF5E56',
  br_green = '#83C746',
  br_yellow = '#EFC541',
  br_blue = '#4F9CFE',
  br_magenta = '#FF81CA',
  br_cyan = '#56D8C9',
  br_orange = '#FA9153',
  br_violet = '#B891F5',
}

local colors = {
  white = theme.fg_1,
  bg = theme.bg_2,
  bg_highlight = theme.bg_2,
  normal = theme.green,
  insert = theme.cyan,
  command = theme.orange,
  visual = theme.violet,
  replace = theme.br_red,
  diffAdd = theme.green,
  diffModified = theme.orange,
  diffDeleted = theme.red,
  trace = theme.orange,
  hint = theme.cyan,
  info = theme.green,
  error = theme.red,
  warn = theme.orange,
  floatBorder = theme.blue,
  selection_caret = theme.blue,
}
return colors
